blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('tips/', views.tips, name='tips'),
    path('archive/', views.archive, name='archive'),
    path('<int:blog_id>/entry/', views.entry, name='entry'),
    path('<int:blog_id>/addcomment/', views.addcomment, name='addcomment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')), 
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

blog/models.py
from django.db import models
from django.utils import timezone

import datetime

class Blog(models.Model):
    title = models.CharField(max_length=128)
    author = models.CharField(max_length=128)
    content = models.TextField()
    posted = models.DateTimeField('date posted')

    def __str__(self):
        return self.title

    def __str__(self):
        return self.author

    def __str__(self):
        return self.content
    
    def posted_date(self):
        return self.posted

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    commenter = models.CharField(max_length=128)
    email = models.EmailField(max_length=128)
    content = models.TextField()
    posted = models.DateTimeField('date posted')
        
    def __str__(self):
        return self.commenter

    def __str__(self):
        return self.email

    def __str__(self):
        return self.content
    
    def posted_date(self):
        return self.posted
    
class About(models.Model):
    current_date = models.DateTimeField('current date')

class Tips(models.Model):
    current_date = models.DateTimeField('current date')

polls/models.py
from django.db import models
from django.utils import timezone

import datetime


class Question(models.Model):
     question_text = models.CharField(max_length=200)
     pub_date = models.DateTimeField('date published')
     
     def __str__(self):
        return self.question_text

     def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from time import strftime

from .models import About, Blog, Comment

def about(request):
    return render(request,
        'blog/about.html', 
        {
            'now': strftime('%c'),
        }
    )

def tips(request):
    return render(request,
        'blog/techtips+css.html', 
        {
            'now': strftime('%c'),
        }
    )

def home(request):

    blogPosts = Blog.objects.order_by('-posted')[:3]

    return render(request,
        'blog/bloghome.html',
        {
            'blogPosts': blogPosts
        }
    )

def archive(request):

    blogPosts = Blog.objects.order_by('-posted')

    return render(request,
        'blog/blogarchive.html',
        {
            'blogPosts': blogPosts
        }
    )

def entry(request, blog_id):
    blogPost = get_object_or_404(Blog, pk=blog_id)

    return render(request,
        'blog/blogentry.html',
        {
            'blogPost': blogPost
        }
    )

def addcomment(request, blog_id):
    blogPost = get_object_or_404(Blog, pk=blog_id)

    try:    
        comment = blogPost.comment_set.get(pk=request.POST['comment'])
    except (KeyError, Comment.DoesNotExist):
        return(render(request,
                'blog/addcomment.html',
                {
                    'blogPost': blogPost,
                }
            )
        )
    else:
        comment.posted = timezone.now()
        comment.save()
        return HttpResponseRedirect(reverse('blog:entry', args=(blogPost.id,)))

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/about.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>about</title>
    </head>

    <body>
        <h3>Todays Date: {{now}}</h3>
        <h1>John Wayne</h1>

        <div>
            <ol>
                <li><a href="{% url 'blog:home' %}">home</a></li>
                <li><a href="{% url 'blog:tips' %}">tips</a></li>
                <li><a href="{% url 'blog:archive' %}">archive</a></li>
            </ol>
        </div>

        <div>   
            <img src="{%static 'blog/images/people-875597_1280.jpg'%}" alt="Self Portrait" class="clientpic">
            <p class="clientdescr">
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum 
                dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            </p>
        </div>

        <div>
            <img src="{%static 'blog/images/cowboy-940083_1280.jpg'%}" alt="I would consider myself a gunslinger" class="hobbies">
            <p class="descr">"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores."</p>
        </div>

        <div>
            <img src="{%static 'blog/images/sunset-3085578_1280.jpg'%}" alt="I enjoy riding horses" class="hobbies">
            <p class="descr">"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores."</p>
        </div>

        <div>
            <img src="{%static 'blog/images/guitar-174931_1280.jpg'%}" alt="I like to play guitar" class="hobbies">
            <p class="descr">"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores."</p>
        </div>
                

    </body>
</html>

blog/templates/blog/addcomment.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>add comment</title>
    </head>

    <body>
        <h1>Add Comment</h1>

        <div class="comments">

            <form action="{% url 'blog:entry' blogPost.pk %}" method="post">
                {% csrf_token %}
                
                <label for="commenter">Full Name:</label>
                <input type="text" name="commenter" id="commenter" ><br><br>

                <label for="email">Email:</label>
                <input type="email" name="email" id="email"><br><br>

                <label for="content">Comment:</label>
                <input type="text" name="content" id="content"><br><br>
                
                <input type="submit" value="Add Comment">
            </form>
        </div>


    </body>
</html>

blog/templates/blog/blogarchive.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>archive</title>
    </head>

    <body>
        <h1>Archive</h1>

        <div>
            <ol>
                <li><a href="{% url 'blog:home' %}">home</a></li>
                <li><a href="{% url 'blog:about' %}">about</a></li>
                <li><a href="{% url 'blog:tips' %}">tips</a></li>
            </ol>
        </div>

        {% if blogPosts %}

            {% for b in blogPosts%}

                <div class="post">

                    <h2>{{b.title}}</h2>
                    <h3>Author: {{b.author}}</h3>
                    <h3>Date: {{b.posted}}</h3>
                    <p>{{b.content | truncatewords:100}}</p>
                    <p>This blog has {{b.comment_set.all | length}} comments ...</p>
                    
                </div>
            {% endfor %}
        {% else %}
                <p>No blog posts are available.</p>
        {% endif %}
    </body>
</html>

blog/templates/blog/blogentry.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>entry</title>
    </head>

    <body>
        <h1>Entry</h1>

        <div>
            <ol>
                <li><a href="{% url 'blog:home' %}">home</a></li>
                <li><a href="{% url 'blog:about' %}">about</a></li>
                <li><a href="{% url 'blog:tips' %}">tips</a></li>
                <li><a href="{% url 'blog:archive' %}">archive</a></li>
            </ol>
        </div>

    {% if blogPost %}
        <div class="post">

            <h2>{{blogPost.title}}</h2>
            <h3>Author: {{blogPost.author}}</h3>
            <h3>Date: {{blogPost.posted}}</h3>
            <p>{{blogPost.content}}</p>
            
        </div>
    {% else %}
        <p>No blog exists with that ID</p>
    {% endif %}
    
    {% if blogPost.comment_set.all %}

        {% for comment in blogPost.comment_set.all reversed %}

            <div class="comments">

                <p class="descr">Commenter: {{comment.commenter}}</p>
                <p class="bold">Email: {{comment.email}}</p>
                <p class="bold">Date: {{comment.posted}}</p>
                <p>{{comment.content}}</p>
                
            </div>
        {% endfor %}
    {% else %}
            <p>No comments exist for this post</p>
    {% endif %}
    
    <div class="comments"><a href="{% url 'blog:addcomment' blogPost.pk%}">Add Comment</a></div>
    </body>
</html>

blog/templates/blog/bloghome.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>home</title>
    </head>

    <body>
        <h1>Home</h1>

        <div>
            <ol>
                <li><a href="{% url 'blog:about' %}">about</a></li>
                <li><a href="{% url 'blog:tips' %}">tips</a></li>
                <li><a href="{% url 'blog:archive' %}">archive</a></li>
            </ol>
        </div>

        {% if blogPosts %}

            {% for b in blogPosts%}

                <div class="post">

                    <h2>{{b.title}}</h2>
                    <h3>Author: {{b.author}}</h3>
                    <h3>Date: {{b.posted}}</h3>
                    <p>{{b.content | truncatewords:100}}</p>
                    <p>This blog has {{b.comment_set.all | length}} comments ...</p>
                    
                </div>
            {% endfor %}
        {% else %}
                <p>No blog posts are available.</p>
        {% endif %}
    </body>
</html>

blog/templates/blog/techtips+css.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{%static 'blog/style.css'%}"/>
        <title>techtips+css</title>
    </head>

    <body>
        <h3>Todays Date: {{now}}</h3>
		<h1>Techtips + Css</h1>

        <div>
            <ol>
                <li><a href="{% url 'blog:home' %}">home</a></li>
                <li><a href="{% url 'blog:about' %}">about</a></li>
                <li><a href="{% url 'blog:archive' %}">archive</a></li>
            </ol>
        </div>

        <div id="htmlelements">
            <h3>HTML Elements</h3>

            <ul id="htmlelementsitems">
                <li><code class="tagtext">&lt;html&gt;</code>: this tag tells the web browser how to interpret the content of your page so it can format and display it properly. Neither a block or in-line element, 
                everything on the webpage goes within this tag. </li>
                <li><code class="tagtext">&lt;head&gt;</code>: this tag is a container for metadata pertaining to the webpage. It is neither a block or in-line element. </li>
                <li><code class="tagtext">&lt;meta&gt;</code>: this tag is a definition for metadata pertaining to the webpage. It is neither a block or in-line element. 
                    Must have <code class="tagtext">&lt;head&gt;</code> as a parent element. </li>
                <li><code class="tagtext">&lt;link&gt;</code>: this tag is used to reference external rescources and is most commonly used for stylesheets. 
                    It is neither a block or in-line element. Must have <code class="tagtext">&lt;head&gt;</code> as a parent element. </li>
                <li><code class="tagtext">&lt;title&gt;</code>: this tag is used for the title that shows up in the tab on the web browser. It is neither a block or in-line element. 
                    Must have <code class="tagtext">&lt;head&gt;</code> as a parent element.</li>
                <li><code class="tagtext">&lt;body&gt;</code>: this tag contains all of the "body" of the webpage so all of the actual content seen by the user. It is neither a block or in-line element.
                    This is the parent element of all of the elements below it in the list. </li>
                <li><code class="tagtext">&lt;h1-h6&gt;</code>: These tags are meant for differing sizes of text. Each one in ascending order gets gradually bigger. This is an example of a block element. </li>
                <li><code class="tagtext">&lt;ul&gt;</code>: this tag stands for "unorderd list" it has <code class="tagtext">&lt;li&gt;</code> tags as its children. This creates a bulleted list in no particular
                    order. This is an exapmle of a block level element. </li>
                <li><code class="tagtext">&lt;ul&gt;</code>: this tag stands for "orderd list" it has <code class="tagtext">&lt;li&gt;</code> tags as its children. This creates a numbered list that is orderd from top
                    to bottom of the <code class="tagtext">&lt;li&gt;</code> tags. This is an example of a block level element.</li>
                <li><code class="tagtext">&lt;li&gt;</code>: this tag stands for "list item" and is has a parent element of either <code class="tagtext">&lt;ul&gt;</code> or <code class="tagtext">&lt;ul&gt;</code>.
                    these <code class="tagtext">&lt;li&gt;</code> tags will show up as either a bulleted list or a numberd list depending on the parent element. This is an example of a block level element. </li>
                <li><code class="tagtext">&lt;div&gt;</code>: this tag is used to represent a division on a webpage and helps to organize information as well as implement css. This is an example of a block level element. </li>
                <li><code class="tagtext">&lt;p&gt;</code>: this tag stands for "paragraph" it is a way to handle multi line text on a webpage efficiently. This is an example of a block level element. </li>
                <li><code class="tagtext">&lt;br&gt;</code>: this tag stands for break in a line so essentially an enter. This tag is empty. </li>
            </ul>
        </div>

        <div id="htmlentities">
            <h3>HTML Entities</h3>

            <ul id="htmlentitiesitems">
                <li><code class="tagtext">&amp;lt;</code>: this is for a <code class="tagtext">&lt;</code> symbul and we use this syntax so the html can render the symbul instead of use it as a tag. </li>
                <li><code class="tagtext">&amp;gt;</code>: this is for a <code class="tagtext">&gt;</code> symbul and we use this syntax so the html can render the symbul instead of use it as a tag. </li>
                <li><code class="tagtext">&amp;apm;</code>: this is for a <code class="tagtext">&gt;</code> symbul and we use this syntax so the html can render the symbul instead of use it as a tag. </li>
                <li><code class="tagtext">&amp;nbsp;</code>: this tag does not have a symbul but is used for a non-breaking space. </li>
                <li><code class="tagtext">&amp;quot;</code>: this is for a <code class="tagtext">&quot;</code> symbul and we use this syntax so the html can render the symbul instead of use it as a tag. </li>
                <li><code class="tagtext">&amp;apos;</code>: this is for a <code class="tagtext">&apos;</code> symbul and we use this syntax so the html can render the symbul instead of use it as a tag. </li>
            </ul>
        </div>

        <div id="cssselectors">
            <h3>Css Selectors</h3>

            <ul id="cssselectorsitems">
                <li><code class="tagtext">element</code>: the element selector is shown by the name of the tag of the element ex(<code class="tagtext">p, div, ul</code>) </li>
                <li><code class="tagtext">class</code>: the class selector is shown by a <code class="tagtext">.</code> before the name of the class ex(<code class="tagtext">.classname</code>) </li>
                <li><code class="tagtext">id</code>: the id selector is shown by a <code class="tagtext">#</code> ex(<code class="tagtext">#idname</code>) </li>

            </ul>
        </div>

        <div id="cssproperties">
            <h3>CSS Properties</h3>

            <ul id="csspropertiesitems">
                <li><code class="tagtext">background-culor</code>: this property is used for the background culor of the selector. </li>
                <li><code class="tagtext">font-size</code>: this property is used for the font size of the selector.</li>
                <li><code class="tagtext">text-align</code>: this property is used for the alignment of the text in the selector. </li>
                <li><code class="tagtext">margin</code>: this property is used to create space around the elements in the selector. </li>
                <li><code class="tagtext">font-weight</code>: this property is used to set the font to buld. </li>
                <li><code class="tagtext">font-family</code>: this property sets the font type for the words in the selector. </li>
                <li><code class="tagtext">padding</code>: this property is used to create space around content inside of the elements that are in the selector. </li>
                <li><code class="tagtext">culor</code>: this property is used to set the culor of the text inside of the selector. </li>
                <li><code class="tagtext">font-style</code>: this property is used to style text with italics or underlined. </li>
                <li><code class="tagtext">width</code>: this property is used to set how much of a page an element will span. </li>

            </ul>
        </div>

    </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>